language: python

python:
  - "2.7"
  - "3.4"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar -xvf nlopt-2.4.2.tar.gz

install:
  - cd nlopt-2.4.2
  - PYTHON=$(which python) ./configure --prefix=$(dirname $(dirname $(which python))) --enable-shared
  - make
  - make install
  - cd $TRAVIS_BUILD_DIR
  - pip install --upgrade pip
  - pip install unipath requests
  - python setup.py install

script:
  - pip freeze
  - py.test

cache:
  - apt
  - pip
  - directories:
    - $HOME/.cache/pip